import { Manrope,Inter,Geist_Mono ,Rethink_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '../context/ThemeContext';
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});
const rethink_sans = Rethink_Sans({
  variable: "--font-rethink_sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${manrope.variable} ${rethink_sans.variable}  ${geistMono.variable}`}>
        <ThemeProvider>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
